// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: vector_tile.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace VectorTile {

  /// <summary>Holder for reflection information generated from vector_tile.proto</summary>
  public static partial class VectorTileReflection {

    #region Descriptor
    /// <summary>File descriptor for vector_tile.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static VectorTileReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChF2ZWN0b3JfdGlsZS5wcm90bxILdmVjdG9yX3RpbGUipQQKBFRpbGUSJwoG",
            "bGF5ZXJzGAMgAygLMhcudmVjdG9yX3RpbGUuVGlsZS5MYXllchq0AQoFVmFs",
            "dWUSFgoMc3RyaW5nX3ZhbHVlGAEgASgJSAASFQoLZmxvYXRfdmFsdWUYAiAB",
            "KAJIABIWCgxkb3VibGVfdmFsdWUYAyABKAFIABITCglpbnRfdmFsdWUYBCAB",
            "KANIABIUCgp1aW50X3ZhbHVlGAUgASgESAASFAoKc2ludF92YWx1ZRgGIAEo",
            "EkgAEhQKCmJvb2xfdmFsdWUYByABKAhIAEINCgt2YWx1ZV9vbmVvZhpfCgdG",
            "ZWF0dXJlEgoKAmlkGAEgASgEEgwKBHRhZ3MYAiADKA0SKAoEdHlwZRgDIAEo",
            "DjIaLnZlY3Rvcl90aWxlLlRpbGUuR2VvbVR5cGUSEAoIZ2VvbWV0cnkYBCAD",
            "KA0amgEKBUxheWVyEg8KB3ZlcnNpb24YDyABKA0SDAoEbmFtZRgBIAEoCRIr",
            "CghmZWF0dXJlcxgCIAMoCzIZLnZlY3Rvcl90aWxlLlRpbGUuRmVhdHVyZRIM",
            "CgRrZXlzGAMgAygJEicKBnZhbHVlcxgEIAMoCzIXLnZlY3Rvcl90aWxlLlRp",
            "bGUuVmFsdWUSDgoGZXh0ZW50GAUgASgNIj8KCEdlb21UeXBlEgsKB1VOS05P",
            "V04QABIJCgVQT0lOVBABEg4KCkxJTkVTVFJJTkcQAhILCgdQT0xZR09OEANC",
            "AkgDYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::VectorTile.Tile), global::VectorTile.Tile.Parser, new[]{ "Layers" }, null, new[]{ typeof(global::VectorTile.Tile.Types.GeomType) }, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::VectorTile.Tile.Types.Value), global::VectorTile.Tile.Types.Value.Parser, new[]{ "StringValue", "FloatValue", "DoubleValue", "IntValue", "UintValue", "SintValue", "BoolValue" }, new[]{ "ValueOneof" }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::VectorTile.Tile.Types.Feature), global::VectorTile.Tile.Types.Feature.Parser, new[]{ "Id", "Tags", "Type", "Geometry" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::VectorTile.Tile.Types.Layer), global::VectorTile.Tile.Types.Layer.Parser, new[]{ "Version", "Name", "Features", "Keys", "Values", "Extent" }, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Tile : pb::IMessage<Tile> {
    private static readonly pb::MessageParser<Tile> _parser = new pb::MessageParser<Tile>(() => new Tile());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Tile> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::VectorTile.VectorTileReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Tile() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Tile(Tile other) : this() {
      layers_ = other.layers_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Tile Clone() {
      return new Tile(this);
    }

    /// <summary>Field number for the "layers" field.</summary>
    public const int LayersFieldNumber = 3;
    private static readonly pb::FieldCodec<global::VectorTile.Tile.Types.Layer> _repeated_layers_codec
        = pb::FieldCodec.ForMessage(26, global::VectorTile.Tile.Types.Layer.Parser);
    private readonly pbc::RepeatedField<global::VectorTile.Tile.Types.Layer> layers_ = new pbc::RepeatedField<global::VectorTile.Tile.Types.Layer>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::VectorTile.Tile.Types.Layer> Layers {
      get { return layers_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Tile);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Tile other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!layers_.Equals(other.layers_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= layers_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      layers_.WriteTo(output, _repeated_layers_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += layers_.CalculateSize(_repeated_layers_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Tile other) {
      if (other == null) {
        return;
      }
      layers_.Add(other.layers_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 26: {
            layers_.AddEntriesFrom(input, _repeated_layers_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the Tile message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      /// <summary>
      /// GeomType is described in section 4.3.4 of the specification
      /// </summary>
      public enum GeomType {
        [pbr::OriginalName("UNKNOWN")] Unknown = 0,
        [pbr::OriginalName("POINT")] Point = 1,
        [pbr::OriginalName("LINESTRING")] Linestring = 2,
        [pbr::OriginalName("POLYGON")] Polygon = 3,
      }

      /// <summary>
      /// Variant type encoding
      /// The use of values is described in section 4.1 of the specification
      /// </summary>
      public sealed partial class Value : pb::IMessage<Value> {
        private static readonly pb::MessageParser<Value> _parser = new pb::MessageParser<Value>(() => new Value());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<Value> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::VectorTile.Tile.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Value() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Value(Value other) : this() {
          switch (other.ValueOneofCase) {
            case ValueOneofOneofCase.StringValue:
              StringValue = other.StringValue;
              break;
            case ValueOneofOneofCase.FloatValue:
              FloatValue = other.FloatValue;
              break;
            case ValueOneofOneofCase.DoubleValue:
              DoubleValue = other.DoubleValue;
              break;
            case ValueOneofOneofCase.IntValue:
              IntValue = other.IntValue;
              break;
            case ValueOneofOneofCase.UintValue:
              UintValue = other.UintValue;
              break;
            case ValueOneofOneofCase.SintValue:
              SintValue = other.SintValue;
              break;
            case ValueOneofOneofCase.BoolValue:
              BoolValue = other.BoolValue;
              break;
          }

          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Value Clone() {
          return new Value(this);
        }

        /// <summary>Field number for the "string_value" field.</summary>
        public const int StringValueFieldNumber = 1;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string StringValue {
          get { return valueOneofCase_ == ValueOneofOneofCase.StringValue ? (string) valueOneof_ : ""; }
          set {
            valueOneof_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            valueOneofCase_ = ValueOneofOneofCase.StringValue;
          }
        }

        /// <summary>Field number for the "float_value" field.</summary>
        public const int FloatValueFieldNumber = 2;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public float FloatValue {
          get { return valueOneofCase_ == ValueOneofOneofCase.FloatValue ? (float) valueOneof_ : 0F; }
          set {
            valueOneof_ = value;
            valueOneofCase_ = ValueOneofOneofCase.FloatValue;
          }
        }

        /// <summary>Field number for the "double_value" field.</summary>
        public const int DoubleValueFieldNumber = 3;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public double DoubleValue {
          get { return valueOneofCase_ == ValueOneofOneofCase.DoubleValue ? (double) valueOneof_ : 0D; }
          set {
            valueOneof_ = value;
            valueOneofCase_ = ValueOneofOneofCase.DoubleValue;
          }
        }

        /// <summary>Field number for the "int_value" field.</summary>
        public const int IntValueFieldNumber = 4;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public long IntValue {
          get { return valueOneofCase_ == ValueOneofOneofCase.IntValue ? (long) valueOneof_ : 0L; }
          set {
            valueOneof_ = value;
            valueOneofCase_ = ValueOneofOneofCase.IntValue;
          }
        }

        /// <summary>Field number for the "uint_value" field.</summary>
        public const int UintValueFieldNumber = 5;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ulong UintValue {
          get { return valueOneofCase_ == ValueOneofOneofCase.UintValue ? (ulong) valueOneof_ : 0UL; }
          set {
            valueOneof_ = value;
            valueOneofCase_ = ValueOneofOneofCase.UintValue;
          }
        }

        /// <summary>Field number for the "sint_value" field.</summary>
        public const int SintValueFieldNumber = 6;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public long SintValue {
          get { return valueOneofCase_ == ValueOneofOneofCase.SintValue ? (long) valueOneof_ : 0L; }
          set {
            valueOneof_ = value;
            valueOneofCase_ = ValueOneofOneofCase.SintValue;
          }
        }

        /// <summary>Field number for the "bool_value" field.</summary>
        public const int BoolValueFieldNumber = 7;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool BoolValue {
          get { return valueOneofCase_ == ValueOneofOneofCase.BoolValue ? (bool) valueOneof_ : false; }
          set {
            valueOneof_ = value;
            valueOneofCase_ = ValueOneofOneofCase.BoolValue;
          }
        }

        private object valueOneof_;
        /// <summary>Enum of possible cases for the "value_oneof" oneof.</summary>
        public enum ValueOneofOneofCase {
          None = 0,
          StringValue = 1,
          FloatValue = 2,
          DoubleValue = 3,
          IntValue = 4,
          UintValue = 5,
          SintValue = 6,
          BoolValue = 7,
        }
        private ValueOneofOneofCase valueOneofCase_ = ValueOneofOneofCase.None;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ValueOneofOneofCase ValueOneofCase {
          get { return valueOneofCase_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void ClearValueOneof() {
          valueOneofCase_ = ValueOneofOneofCase.None;
          valueOneof_ = null;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as Value);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(Value other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (StringValue != other.StringValue) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(FloatValue, other.FloatValue)) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(DoubleValue, other.DoubleValue)) return false;
          if (IntValue != other.IntValue) return false;
          if (UintValue != other.UintValue) return false;
          if (SintValue != other.SintValue) return false;
          if (BoolValue != other.BoolValue) return false;
          if (ValueOneofCase != other.ValueOneofCase) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (valueOneofCase_ == ValueOneofOneofCase.StringValue) hash ^= StringValue.GetHashCode();
          if (valueOneofCase_ == ValueOneofOneofCase.FloatValue) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(FloatValue);
          if (valueOneofCase_ == ValueOneofOneofCase.DoubleValue) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(DoubleValue);
          if (valueOneofCase_ == ValueOneofOneofCase.IntValue) hash ^= IntValue.GetHashCode();
          if (valueOneofCase_ == ValueOneofOneofCase.UintValue) hash ^= UintValue.GetHashCode();
          if (valueOneofCase_ == ValueOneofOneofCase.SintValue) hash ^= SintValue.GetHashCode();
          if (valueOneofCase_ == ValueOneofOneofCase.BoolValue) hash ^= BoolValue.GetHashCode();
          hash ^= (int) valueOneofCase_;
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (valueOneofCase_ == ValueOneofOneofCase.StringValue) {
            output.WriteRawTag(10);
            output.WriteString(StringValue);
          }
          if (valueOneofCase_ == ValueOneofOneofCase.FloatValue) {
            output.WriteRawTag(21);
            output.WriteFloat(FloatValue);
          }
          if (valueOneofCase_ == ValueOneofOneofCase.DoubleValue) {
            output.WriteRawTag(25);
            output.WriteDouble(DoubleValue);
          }
          if (valueOneofCase_ == ValueOneofOneofCase.IntValue) {
            output.WriteRawTag(32);
            output.WriteInt64(IntValue);
          }
          if (valueOneofCase_ == ValueOneofOneofCase.UintValue) {
            output.WriteRawTag(40);
            output.WriteUInt64(UintValue);
          }
          if (valueOneofCase_ == ValueOneofOneofCase.SintValue) {
            output.WriteRawTag(48);
            output.WriteSInt64(SintValue);
          }
          if (valueOneofCase_ == ValueOneofOneofCase.BoolValue) {
            output.WriteRawTag(56);
            output.WriteBool(BoolValue);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (valueOneofCase_ == ValueOneofOneofCase.StringValue) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(StringValue);
          }
          if (valueOneofCase_ == ValueOneofOneofCase.FloatValue) {
            size += 1 + 4;
          }
          if (valueOneofCase_ == ValueOneofOneofCase.DoubleValue) {
            size += 1 + 8;
          }
          if (valueOneofCase_ == ValueOneofOneofCase.IntValue) {
            size += 1 + pb::CodedOutputStream.ComputeInt64Size(IntValue);
          }
          if (valueOneofCase_ == ValueOneofOneofCase.UintValue) {
            size += 1 + pb::CodedOutputStream.ComputeUInt64Size(UintValue);
          }
          if (valueOneofCase_ == ValueOneofOneofCase.SintValue) {
            size += 1 + pb::CodedOutputStream.ComputeSInt64Size(SintValue);
          }
          if (valueOneofCase_ == ValueOneofOneofCase.BoolValue) {
            size += 1 + 1;
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(Value other) {
          if (other == null) {
            return;
          }
          switch (other.ValueOneofCase) {
            case ValueOneofOneofCase.StringValue:
              StringValue = other.StringValue;
              break;
            case ValueOneofOneofCase.FloatValue:
              FloatValue = other.FloatValue;
              break;
            case ValueOneofOneofCase.DoubleValue:
              DoubleValue = other.DoubleValue;
              break;
            case ValueOneofOneofCase.IntValue:
              IntValue = other.IntValue;
              break;
            case ValueOneofOneofCase.UintValue:
              UintValue = other.UintValue;
              break;
            case ValueOneofOneofCase.SintValue:
              SintValue = other.SintValue;
              break;
            case ValueOneofOneofCase.BoolValue:
              BoolValue = other.BoolValue;
              break;
          }

          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                StringValue = input.ReadString();
                break;
              }
              case 21: {
                FloatValue = input.ReadFloat();
                break;
              }
              case 25: {
                DoubleValue = input.ReadDouble();
                break;
              }
              case 32: {
                IntValue = input.ReadInt64();
                break;
              }
              case 40: {
                UintValue = input.ReadUInt64();
                break;
              }
              case 48: {
                SintValue = input.ReadSInt64();
                break;
              }
              case 56: {
                BoolValue = input.ReadBool();
                break;
              }
            }
          }
        }

      }

      /// <summary>
      /// Features are described in section 4.2 of the specification
      /// </summary>
      public sealed partial class Feature : pb::IMessage<Feature> {
        private static readonly pb::MessageParser<Feature> _parser = new pb::MessageParser<Feature>(() => new Feature());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<Feature> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::VectorTile.Tile.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Feature() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Feature(Feature other) : this() {
          id_ = other.id_;
          tags_ = other.tags_.Clone();
          type_ = other.type_;
          geometry_ = other.geometry_.Clone();
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Feature Clone() {
          return new Feature(this);
        }

        /// <summary>Field number for the "id" field.</summary>
        public const int IdFieldNumber = 1;
        private ulong id_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ulong Id {
          get { return id_; }
          set {
            id_ = value;
          }
        }

        /// <summary>Field number for the "tags" field.</summary>
        public const int TagsFieldNumber = 2;
        private static readonly pb::FieldCodec<uint> _repeated_tags_codec
            = pb::FieldCodec.ForUInt32(18);
        private readonly pbc::RepeatedField<uint> tags_ = new pbc::RepeatedField<uint>();
        /// <summary>
        /// Tags of this feature are encoded as repeated pairs of
        /// integers.
        /// A detailed description of tags is located in sections
        /// 4.2 and 4.4 of the specification
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pbc::RepeatedField<uint> Tags {
          get { return tags_; }
        }

        /// <summary>Field number for the "type" field.</summary>
        public const int TypeFieldNumber = 3;
        private global::VectorTile.Tile.Types.GeomType type_ = 0;
        /// <summary>
        /// The type of geometry stored in this feature.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::VectorTile.Tile.Types.GeomType Type {
          get { return type_; }
          set {
            type_ = value;
          }
        }

        /// <summary>Field number for the "geometry" field.</summary>
        public const int GeometryFieldNumber = 4;
        private static readonly pb::FieldCodec<uint> _repeated_geometry_codec
            = pb::FieldCodec.ForUInt32(34);
        private readonly pbc::RepeatedField<uint> geometry_ = new pbc::RepeatedField<uint>();
        /// <summary>
        /// Contains a stream of commands and parameters (vertices).
        /// A detailed description on geometry encoding is located in 
        /// section 4.3 of the specification.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pbc::RepeatedField<uint> Geometry {
          get { return geometry_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as Feature);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(Feature other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Id != other.Id) return false;
          if(!tags_.Equals(other.tags_)) return false;
          if (Type != other.Type) return false;
          if(!geometry_.Equals(other.geometry_)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (Id != 0UL) hash ^= Id.GetHashCode();
          hash ^= tags_.GetHashCode();
          if (Type != 0) hash ^= Type.GetHashCode();
          hash ^= geometry_.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (Id != 0UL) {
            output.WriteRawTag(8);
            output.WriteUInt64(Id);
          }
          tags_.WriteTo(output, _repeated_tags_codec);
          if (Type != 0) {
            output.WriteRawTag(24);
            output.WriteEnum((int) Type);
          }
          geometry_.WriteTo(output, _repeated_geometry_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (Id != 0UL) {
            size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Id);
          }
          size += tags_.CalculateSize(_repeated_tags_codec);
          if (Type != 0) {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
          }
          size += geometry_.CalculateSize(_repeated_geometry_codec);
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(Feature other) {
          if (other == null) {
            return;
          }
          if (other.Id != 0UL) {
            Id = other.Id;
          }
          tags_.Add(other.tags_);
          if (other.Type != 0) {
            Type = other.Type;
          }
          geometry_.Add(other.geometry_);
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                Id = input.ReadUInt64();
                break;
              }
              case 18:
              case 16: {
                tags_.AddEntriesFrom(input, _repeated_tags_codec);
                break;
              }
              case 24: {
                Type = (global::VectorTile.Tile.Types.GeomType) input.ReadEnum();
                break;
              }
              case 34:
              case 32: {
                geometry_.AddEntriesFrom(input, _repeated_geometry_codec);
                break;
              }
            }
          }
        }

      }

      /// <summary>
      /// Layers are described in section 4.1 of the specification
      /// </summary>
      public sealed partial class Layer : pb::IMessage<Layer> {
        private static readonly pb::MessageParser<Layer> _parser = new pb::MessageParser<Layer>(() => new Layer());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<Layer> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::VectorTile.Tile.Descriptor.NestedTypes[2]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Layer() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Layer(Layer other) : this() {
          version_ = other.version_;
          name_ = other.name_;
          features_ = other.features_.Clone();
          keys_ = other.keys_.Clone();
          values_ = other.values_.Clone();
          extent_ = other.extent_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Layer Clone() {
          return new Layer(this);
        }

        /// <summary>Field number for the "version" field.</summary>
        public const int VersionFieldNumber = 15;
        private uint version_;
        /// <summary>
        /// Any compliant implementation must first read the version
        /// number encoded in this message and choose the correct
        /// implementation for this version number before proceeding to
        /// decode other parts of this message.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public uint Version {
          get { return version_; }
          set {
            version_ = value;
          }
        }

        /// <summary>Field number for the "name" field.</summary>
        public const int NameFieldNumber = 1;
        private string name_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Name {
          get { return name_; }
          set {
            name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "features" field.</summary>
        public const int FeaturesFieldNumber = 2;
        private static readonly pb::FieldCodec<global::VectorTile.Tile.Types.Feature> _repeated_features_codec
            = pb::FieldCodec.ForMessage(18, global::VectorTile.Tile.Types.Feature.Parser);
        private readonly pbc::RepeatedField<global::VectorTile.Tile.Types.Feature> features_ = new pbc::RepeatedField<global::VectorTile.Tile.Types.Feature>();
        /// <summary>
        /// The actual features in this tile.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pbc::RepeatedField<global::VectorTile.Tile.Types.Feature> Features {
          get { return features_; }
        }

        /// <summary>Field number for the "keys" field.</summary>
        public const int KeysFieldNumber = 3;
        private static readonly pb::FieldCodec<string> _repeated_keys_codec
            = pb::FieldCodec.ForString(26);
        private readonly pbc::RepeatedField<string> keys_ = new pbc::RepeatedField<string>();
        /// <summary>
        /// Dictionary encoding for keys
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pbc::RepeatedField<string> Keys {
          get { return keys_; }
        }

        /// <summary>Field number for the "values" field.</summary>
        public const int ValuesFieldNumber = 4;
        private static readonly pb::FieldCodec<global::VectorTile.Tile.Types.Value> _repeated_values_codec
            = pb::FieldCodec.ForMessage(34, global::VectorTile.Tile.Types.Value.Parser);
        private readonly pbc::RepeatedField<global::VectorTile.Tile.Types.Value> values_ = new pbc::RepeatedField<global::VectorTile.Tile.Types.Value>();
        /// <summary>
        /// Dictionary encoding for values
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pbc::RepeatedField<global::VectorTile.Tile.Types.Value> Values {
          get { return values_; }
        }

        /// <summary>Field number for the "extent" field.</summary>
        public const int ExtentFieldNumber = 5;
        private uint extent_;
        /// <summary>
        /// Although this is an "optional" field it is required by the specification.
        /// See https://github.com/mapbox/vector-tile-spec/issues/47
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public uint Extent {
          get { return extent_; }
          set {
            extent_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as Layer);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(Layer other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Version != other.Version) return false;
          if (Name != other.Name) return false;
          if(!features_.Equals(other.features_)) return false;
          if(!keys_.Equals(other.keys_)) return false;
          if(!values_.Equals(other.values_)) return false;
          if (Extent != other.Extent) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (Version != 0) hash ^= Version.GetHashCode();
          if (Name.Length != 0) hash ^= Name.GetHashCode();
          hash ^= features_.GetHashCode();
          hash ^= keys_.GetHashCode();
          hash ^= values_.GetHashCode();
          if (Extent != 0) hash ^= Extent.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (Name.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Name);
          }
          features_.WriteTo(output, _repeated_features_codec);
          keys_.WriteTo(output, _repeated_keys_codec);
          values_.WriteTo(output, _repeated_values_codec);
          if (Extent != 0) {
            output.WriteRawTag(40);
            output.WriteUInt32(Extent);
          }
          if (Version != 0) {
            output.WriteRawTag(120);
            output.WriteUInt32(Version);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (Version != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Version);
          }
          if (Name.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
          }
          size += features_.CalculateSize(_repeated_features_codec);
          size += keys_.CalculateSize(_repeated_keys_codec);
          size += values_.CalculateSize(_repeated_values_codec);
          if (Extent != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Extent);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(Layer other) {
          if (other == null) {
            return;
          }
          if (other.Version != 0) {
            Version = other.Version;
          }
          if (other.Name.Length != 0) {
            Name = other.Name;
          }
          features_.Add(other.features_);
          keys_.Add(other.keys_);
          values_.Add(other.values_);
          if (other.Extent != 0) {
            Extent = other.Extent;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                Name = input.ReadString();
                break;
              }
              case 18: {
                features_.AddEntriesFrom(input, _repeated_features_codec);
                break;
              }
              case 26: {
                keys_.AddEntriesFrom(input, _repeated_keys_codec);
                break;
              }
              case 34: {
                values_.AddEntriesFrom(input, _repeated_values_codec);
                break;
              }
              case 40: {
                Extent = input.ReadUInt32();
                break;
              }
              case 120: {
                Version = input.ReadUInt32();
                break;
              }
            }
          }
        }

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
